### ISSUE TITLE
Potentially issue with OpenGL Games

### ISSUE THREAD

**Issue by ZetaHunter** [solus-project/budgie-desktop#190]
I've been trying to launch Team Fortress 2 on my laptop with Optimus graphics (Intel and GTX700M card) and whatever I run with optirun (I have bumblebee) or just with cpu, the game opens but whenever I click anywhere in it, it will just hide itself and how desktop instead.

**Comment by ikeydoherty** [comment]
What version of GTK/Mutter you on? Remember we're targeting 3.14 with Budgie atm, afaik you're on 3.16 on Arch ? Could have a lot to do with it. OpenGL games work fine for me on Solus (KSP and Minecraft)

**Comment by ZetaHunter** [comment]
Yeah, that might be cause for it, is there actually any plans for 3.16 just yet?

**Comment by ikeydoherty** [comment]
Probably tonight

**Comment by ZetaHunter** [comment]
That sounds awesome, thanks for the quick reply's!

**Comment by ikeydoherty** [comment]
So yeah - we're working towards 3.16 tonight: https://github.com/solus-project/repository/commits/master

**Comment by ZetaHunter** [comment]
That's a lot of commits in an hour!
Nice job, I will be sure to pull it tomorrow and check it all out!

**Comment by ikeydoherty** [comment]
Once we hit 3.16 in Solus we'll then fix up budgie-desktop to work fully with 3.16 - changes expected. Also check budgie-desktop's master - a lot of the old crap for Ubuntu got dropped permanently :)

**Comment by ikeydoherty** [comment]
Games are working fine on Solus with Mutter/GTK/3.16 (sidenote: This is not going to fly.)

![screenshot from 2015-04-16 23-30-43](https://cloud.githubusercontent.com/assets/164489/7192790/b01fab42-e490-11e4-88be-ce1625d15721.png)

**Comment by ZetaHunter** [comment]
Somehow the changes seem to have broken it for me.
```
...
/usr/include/glib-2.0/gio/glistmodel.h:36:21: error: redefinition of typedef ‘GListModel’ [-Werror=pedantic]
 G_DECLARE_INTERFACE(GListModel, g_list_model, G, LIST_MODEL, GObject)
                     ^
/usr/include/glib-2.0/gobject/gtype.h:1559:35: note: in definition of macro ‘G_DECLARE_INTERFACE’
   typedef struct _##ModuleObjName ModuleObjName;                                                           \
                                   ^
In file included from /usr/include/glib-2.0/gio/gio.h:26:0,
                 from budgie-session-dialog-resources.c:1:
/usr/include/glib-2.0/gio/giotypes.h:64:47: note: previous declaration of ‘GListModel’ was here
 typedef struct _GListModel                    GListModel;
                                               ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from budgie-session-dialog-resources.c:1:
/usr/include/glib-2.0/gio/gliststore.h:36:22: error: redefinition of typedef ‘GListStore’ [-Werror=pedantic]
 G_DECLARE_FINAL_TYPE(GListStore, g_list_store, G, LIST_STORE, GObject)
                      ^
/usr/include/glib-2.0/gobject/gtype.h:1390:35: note: in definition of macro ‘G_DECLARE_FINAL_TYPE’
   typedef struct _##ModuleObjName ModuleObjName;                                                         \
                                   ^
In file included from /usr/include/glib-2.0/gio/gio.h:26:0,
                 from budgie-session-dialog-resources.c:1:
/usr/include/glib-2.0/gio/giotypes.h:65:47: note: previous declaration of ‘GListStore’ was here
 typedef struct _GListStore                    GListStore;
                                               ^
cc1: all warnings being treated as errors
Makefile:632: recipe for target 'budgie_session_dialog-budgie-session-dialog-resources.o' failed
make[3]: *** [budgie_session_dialog-budgie-session-dialog-resources.o] Error 1
make[3]: Leaving directory '/home/zeta/projects/budgie-desktop/session'
Makefile:469: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/zeta/projects/budgie-desktop/session'
Makefile:475: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zeta/projects/budgie-desktop'
Makefile:407: recipe for target 'all' failed
make: *** [all] Error 2
```
```
[zeta:~/projects/budgie-desktop]$ vala --version 
Vala 0.28.0
[zeta:~/projects/budgie-desktop]$ mutter --version
mutter 3.16.1.1
[zeta:~/projects/budgie-desktop]$ pacrep gtk3 | grep "Version"
Version        : 3.16.2-1

```

**Comment by ikeydoherty** [comment]
Up or down this will be resolved tonight. We updated to pretty much the same versions on Solus. Naturally we'll hit the same issue :)

**Comment by ikeydoherty** [comment]
We're not the only ones: https://launchpadlibrarian.net/202043696/buildlog_ubuntu-vivid-arm64.ibus_1.5.9-1ubuntu2_BUILDING.txt.gz

**Comment by ikeydoherty** [comment]
Fixed

**Comment by ZetaHunter** [comment]
Confirming #192 has fixed the issue of compilation.
I have tried to play Team Fortress 2 again, but seem to still have the issue.
Whenever I click anywhere in the OpenGL window (even in full screen) it will "minimize" itself.

**Comment by ikeydoherty** [comment]
OK so I can confirm, can you see if this happens in a smaller freely available game ?

**Comment by ZetaHunter** [comment]
Got anything in mind? I mean TF2 is free but not small by any means.
I have a ton of indie shit in my library and some stuff in Humble Bundle, but I guess there are some games on Aur too.

**Comment by ZetaHunter** [comment]
I've tried playing Strike Suit Zero - same issue.
But when I tried Starbound, there dosen't seem to be any issue.
All of those games have been downloaded legitimately from Steam and testing both in primusrun and just with CPU.

**Comment by ikeydoherty** [comment]
Unable to recreate issue here.. Even with a completely updated X stack in Solus.
Distro/driver specific maybe? Or even primusrun itself..

**Comment by ikeydoherty** [comment]
Closing due to a lack of response (posted to G+ and nobody else can recreate)
